# prometheus.yml

global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: fastapi
    honor_labels: true
    static_configs:
    - targets:
      - 34.64.86.255:5000  # metrics from model

  - job_name: 'jenkins'
    scrape_interval: 10s
    scrape_timeout: 60s
    metrics_path: /prometheus/
    static_configs:
      - targets:
          - 34.64.84.255:8080